language: python
dist: xenial
sudo: required
cache: 
  - pip
python:
    - 2.7
    - 3.4
    - 3.5
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mongodb-server mysql-server rabbitmq-server redis-server zookeeper mongodb couchdb couchdb-bin npm ceph librados-dev python-dev gcc
  # - sudo gem install fakes3  # NOTE(sileht): fakes3 looks not installed correctly
  - sudo npm install s3rver -g
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
  - sudo dpkg -i influxdb_0.13.0_amd64.deb
  # zkEnv.sh can't be overriden with the deb version of zookeeper, this workaround that
  - sudo chmod 777 /var/log/zookeeper
  - wget http://apache.crihan.fr/dist/kafka/0.10.1.0/kafka_2.11-0.10.1.0.tgz -O /opt/kafka.tar.gz
  - tar -xzf /opt/kafka.tar.gz -C /opt
  - ln -s /opt/kafka_2.11-0.10.1.0 /opt/kafka
install:
    # The install requirements in travis virtualenv that will be cached
  - pip install tox-travis .[test]
script: tox -v -- $PIFPAF_TESTS
# notifications:
#  email:
#    - julien@danjou.info
