language: python
dist: xenial
sudo: required
cache: 
  - pip
python:
    - 2.7
    - 3.4
    - 3.5
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mongodb-server mysql-server rabbitmq-server redis-server zookeeper mongodb couchdb couchdb-bin npm ceph librados-dev python-dev gcc
  # - sudo gem install fakes3  # NOTE(sileht): fakes3 looks not installed correctly
  - sudo npm install s3rver -g
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
  - sudo dpkg -i influxdb_0.13.0_amd64.deb
install:
    # The install requirements in travis virtualenv that will be cached
  - pip install tox-travis .[test]
script: tox -v -- $PIFPAF_TESTS
# notifications:
#  email:
#    - julien@danjou.info
