language: python
addons:
  apt:
    packages:
    - elasticsearch
    - redis-server
    - redis-sentinel
    - zookeeper
    - influxdb
    - etcd
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
env:
  global:
    - TRAVIS=1
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=pep8
install: pip install tox gnocchi[postgresql,file]
script: tox
notifications:
  email:
    - julien@danjou.info
